---
#build the java app and transfer it on the prod env
- hosts: build
  become: yes
  tasks:
    - name: Ensure git is present
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure maven is present
      apt:
        name: maven
        state: present
        update_cache: yes

    - name: Catch the application from git
      git:
        repo: http://github.com/koddas/war-web-project.git
        dest: /usr/war-web-project

- hosts: prod
  become: yes
  tasks:
    apt:
      name: tomcat9
      state: present
      update_cache: yes

    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started
    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started