---
- hosts: prod
  become: yes
  tasks:
    apt:
      name: tomcat9
      state: present
      update_cache: yes

- hosts: build
  become: yes
  tasks:
    - name: Ensure git is present
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure maven is present
      apt:
        name: maven
        state: present
        update_cache: yes

    - name: Catch the application from git
      git:
        repo: http://github.com/koddas/war-web-project.git
        dest: /usr/war-web-project

    - name: Run mvn clean boxfuse folder
      shell:
        cmd: mvn clean package
        chdir: /usr/war-web-project

    - name: Align the folders between build and prod
      synchronize:
        mode: pull
        src: /usr/war-web-project/target/*war
        dest: /var/lib/tomcat9/webapps/
      delegate_to: "{{groups['prod'][0]}}"
- hosts: prod
  become: yes
  tasks:
  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started
...