---
#prod infrastructure
- hosts: prod
  become: yes
  tasks:
    - name: Ensure tomcat9 is present
      apt:
        name: tomcat9
        state: present
        update_cache: yes

#build infrastructure
- hosts: build
  become: yes
  tasks:
    - name: Ensure git is present
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure maven is present
      apt:
        name: maven
        state: present
        update_cache: yes

    - name: Catch the application from git
      git:
        repo: http://github.com/koddas/war-web-project.git
        dest: /usr/war-web-project

    - name: Run mvn clean the app's folder
      shell:
        cmd: mvn clean package
        chdir: /usr/war-web-project

    - name: Synchronization of build and prod directories
      synchronize:
        mode: pull
        src: rsync://usr/war-web-project/target/wwp-1.0.0.war
        dest: /var/lib/tomcat9/webapps/
      delegate_to: "{{ groups['prod'][0] }}"

#prod check
- hosts: prod
  become: yes
  tasks:

    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started
...